# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3.3],[4,5,6.6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array1 = np.random.randint(0,10,size=(7,2))
random_array1

array([[8, 0],
       [8, 9],
       [6, 2],
       [2, 9],
       [7, 2],
       [5, 0],
       [8, 8]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2 = np.random.random((3,5))
random_array2

array([[0.91293841, 0.22953413, 0.82766976, 0.63312789, 0.12852609],
       [0.88431777, 0.14679175, 0.10072577, 0.51125813, 0.55199745],
       [0.18082478, 0.42621362, 0.42242062, 0.99858885, 0.27019924]])

In [16]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3 = np.random.randint(0,10,size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array4 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array4), random_array4.ndim

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), 2)

In [22]:
# Find the 0'th index of the latest array you created
random_array4, random_array4[0]

(array([[7, 8, 3, 1, 4, 2, 8],
        [4, 2, 6, 6, 4, 6, 2],
        [2, 4, 8, 7, 9, 8, 5]]),
 array([7, 8, 3, 1, 4, 2, 8]))

In [24]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [25]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[:2, :2]

array([[7, 8],
       [4, 2]])

In [26]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5 = np.random.randint(0,10,(3,5))
ones = np.ones((3,5))
random_array5, ones

(array([[1, 4, 7, 9, 8],
        [8, 0, 8, 6, 8],
        [7, 0, 7, 7, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [27]:
# Add the two arrays together
random_array5 + ones

array([[ 2.,  5.,  8., 10.,  9.],
       [ 9.,  1.,  9.,  7.,  9.],
       [ 8.,  1.,  8.,  8.,  3.]])

In [29]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# Try add the array of ones and the other most recent array together
random_array5 + ones2.reshape((3,5))

array([[ 2.,  5.,  8., 10.,  9.],
       [ 9.,  1.,  9.,  7.,  9.],
       [ 8.,  1.,  8.,  8.,  3.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [33]:
# Create another array of ones of shape (3, 5)
ones3 = np.ones((3,5))
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# Subtract the new array of ones from the other most recent array
random_array5 - ones3

array([[ 0.,  3.,  6.,  8.,  7.],
       [ 7., -1.,  7.,  5.,  7.],
       [ 6., -1.,  6.,  6.,  1.]])

In [36]:
random_array5.shape, ones3.shape

((3, 5), (3, 5))

In [35]:
# Multiply the ones array with the latest array
random_array5 * ones3

array([[1., 4., 7., 9., 8.],
       [8., 0., 8., 6., 8.],
       [7., 0., 7., 7., 2.]])

In [37]:
# Take the latest array to the power of 2 using '**'
random_array5 ** 2

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [38]:
# Do the same thing with np.square()
np.square(random_array5)

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [39]:
# Find the mean of the latest array using np.mean()
np.mean(random_array5)

5.466666666666667

In [40]:
# Find the maximum of the latest array using np.max()
np.max(random_array5)

9

In [41]:
# Find the minimum of the latest array using np.min()
np.min(random_array5)

0

In [42]:
# Find the standard deviation of the latest array
np.std(random_array5)

3.0739045022396008

In [43]:
# Find the variance of the latest array
np.var(random_array5)

9.448888888888888

In [46]:
# Reshape the latest array to (3, 5, 1)
random_array5.reshape(3,5,1)

array([[[1],
        [4],
        [7],
        [9],
        [8]],

       [[8],
        [0],
        [8],
        [6],
        [8]],

       [[7],
        [0],
        [7],
        [7],
        [2]]])

In [47]:
# Transpose the latest array
random_array5.T

array([[1, 8, 7],
       [4, 0, 0],
       [7, 8, 7],
       [9, 6, 7],
       [8, 8, 2]])

What does the transpose do?

In [48]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array6 = np.random.randint(0,10,(3,3))
random_array7 = np.random.randint(0,10,(3,2))
random_array6, random_array7

(array([[0, 7, 2],
        [2, 0, 4],
        [9, 6, 9]]),
 array([[8, 6],
        [8, 7],
        [1, 0]]))

In [49]:
# Perform a dot product on the two newest arrays you created
random_array6.dot(random_array7)

array([[ 58,  49],
       [ 20,  12],
       [129,  96]])

In [50]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array8 = np.random.randint(0,10,(4,3))
random_array9 = np.random.randint(0,10,(4,3))
random_array8, random_array9

(array([[6, 6, 7],
        [4, 2, 7],
        [5, 2, 0],
        [2, 4, 2]]),
 array([[0, 4, 9],
        [6, 6, 8],
        [9, 9, 2],
        [6, 0, 3]]))

In [51]:
# Perform a dot product on the two newest arrays you created
random_array8.dot(random_array9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [52]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
random_array8.dot(random_array9.T)

array([[ 87, 128, 122,  57],
       [ 71,  92,  68,  45],
       [  8,  42,  63,  30],
       [ 34,  52,  58,  18]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [53]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array8.shape, random_array9.shape

((4, 3), (4, 3))

In [54]:
# Compare the two arrays with '>'
random_array8 > random_array9

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [55]:
# Compare the two arrays with '>='
random_array8 >= random_array9

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [56]:
# Find which elements of the first array are greater than 7
a1 > 7

array([False, False, False])

In [57]:
# Which parts of each array are equal? (try using '==')
a1 == a1

array([ True,  True,  True])

In [62]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array1)

array([[0, 8],
       [8, 9],
       [2, 6],
       [2, 9],
       [2, 7],
       [0, 5],
       [8, 8]])

In [66]:
random_array2

array([[0.91293841, 0.22953413, 0.82766976, 0.63312789, 0.12852609],
       [0.88431777, 0.14679175, 0.10072577, 0.51125813, 0.55199745],
       [0.18082478, 0.42621362, 0.42242062, 0.99858885, 0.27019924]])

In [67]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array2)

array([[4, 1, 3, 2, 0],
       [2, 1, 3, 4, 0],
       [0, 4, 2, 1, 3]], dtype=int64)

In [70]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array2)

13

In [71]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array2)

7

In [73]:
random_array2

array([[0.91293841, 0.22953413, 0.82766976, 0.63312789, 0.12852609],
       [0.88431777, 0.14679175, 0.10072577, 0.51125813, 0.55199745],
       [0.18082478, 0.42621362, 0.42242062, 0.99858885, 0.27019924]])

In [72]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array2,axis=1)

array([0, 0, 3], dtype=int64)

In [74]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array2,axis=0)

array([2, 1, 1, 1, 0], dtype=int64)

In [86]:
# Create an array of normally distributed random numbers
normally_dist__random_array = np.random.normal(0,0.1,(5,5))
normally_dist__random_array 

array([[ 0.01498337,  0.01409074,  0.03544196, -0.18803126,  0.0966392 ],
       [-0.05109445,  0.12103986, -0.0151236 , -0.03745216, -0.12912161],
       [-0.07655094,  0.04223138, -0.13079143, -0.19905995, -0.08575489],
       [ 0.08400054,  0.17812911, -0.06774157, -0.15488287, -0.03431291],
       [ 0.01838555,  0.05778971,  0.21346412,  0.02268488,  0.16554616]])

In [91]:
# Create an array with 10 evenly spaced numbers between 1 and 100
# evenly_space_array = np.arange(1,100,10)
evenly_space_array = np.linspace(1, 100, 10)
evenly_space_array


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.